server:
  port: 8080
  servlet:
    context-path: /t

spring:
    profiles:
      active: dev
    application:
      name: base-start
    mvc:
      throw-exception-if-no-handler-found: true
      #### 只允许通过static目录静态资源访问，这样不会有默认的RecourseHandler,而导致无法正常404抛出异常
      #### 使用之后，springboot默认的资源根路径，都需要添加/static前缀
      static-path-pattern: /static/**

debug: true

logging:
  config: "classpath:config/log4j2-${spring.profiles.active}.xml"


